"""
Figure data for sections 8 to 11 (components, acoustics, near field,
dynamics). Writes results/fig/c_*.dat tables and results/fig/c_geom.tex,
a file of \\def macros with the design's geometry and operating point that
the TikZ drawings are dimensioned from.
"""

from __future__ import annotations

import math
import os

import numpy as np

from _common import ROOT, base_params, default_out, write_table  # noqa: F401

from flyingscreen import acoustics  # noqa: E402
from flyingscreen import components as C  # noqa: E402
from flyingscreen.dynamics import build_vehicle  # noqa: E402


def _defs(out_dir: str, name: str, values: dict) -> None:
    """\\def macros, safe to \\input more than once."""
    path = os.path.join(out_dir, name + ".tex")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("% Generated by paper/figures/gen_c.py. Do not edit by hand.\n")
        for k, v in values.items():
            fh.write("\\def\\%s{%s}\n" % (k, v))


def generate(out_dir: str) -> None:
    p = base_params()
    N = int(round(float(p["N_rotors"])))
    g = float(p["g"])
    closed = C.close_first_principles(p)
    m, m_bat = closed["m"], closed["m_bat"]
    pr = C.propulsion(p, m)
    hov = pr.rotor_hover
    m_tip = pr.m_motor_each + (pr.m_esc + pr.m_props) / N
    arm = C.arm_structure(p, m, m_tip=m_tip)
    veh = build_vehicle(p, m, m_bat)
    inert = C.inertia(p, m, arm, m_tip)
    surf = C.surface_effects(p)
    inter = C.interference_factor(p)
    R = float(p["D_rotor"]) / 2.0

    # -- wall thickness requirements against gross mass ------------------------
    rows = []
    for mm in np.geomspace(0.3, 8.0, 90):
        a = C.arm_structure(p, float(mm), m_tip=m_tip)
        rows.append((mm, 1e3 * a.wall_stress, 1e3 * a.wall_stiff,
                     1e3 * float(p["wall_min"]), 1e3 * a.wall))
    write_table(out_dir, "c_wall", ["m", "tsigma", "tdelta", "tmin", "t"], rows)

    # -- battery: energy and power requirements against session length -------
    rows = []
    cross = float("nan")
    prev = None
    for tmin in np.linspace(1.0, 70.0, 70):
        q = dict(p, t_f=60.0 * float(tmin))
        r = C.close_first_principles(q)
        if not r["feasible"]:
            continue
        rb = C.required_battery(q, r["m"])
        rows.append((tmin, r["m"], rb["m_energy"], rb["m_power"], rb["m_bat"]))
        diff = rb["m_energy"] - rb["m_power"]
        if prev is not None and prev[1] < 0 <= diff:
            t0, d0 = prev
            cross = t0 + (tmin - t0) * (-d0) / (diff - d0)
        prev = (tmin, diff)
    write_table(out_dir, "c_battery", ["tf", "m", "menergy", "mpower", "mbat"], rows)

    # -- room acoustics against distance --------------------------------------
    rep = acoustics.report(p, hov, float(N), C._SPL_REF)
    L_W = rep["L_WA"]
    Rroom = rep["room"]["R"]
    Q = acoustics.Q_HEMI
    rows = []
    for r_ in np.geomspace(0.1, 8.0, 140):
        direct = L_W + 10.0 * math.log10(Q / (4.0 * math.pi * r_ * r_))
        reverb = L_W + 10.0 * math.log10(4.0 / Rroom)
        total = L_W + 10.0 * math.log10(Q / (4.0 * math.pi * r_ * r_) + 4.0 / Rroom)
        rows.append((r_, direct, reverb, total))
    write_table(out_dir, "c_room", ["r", "direct", "reverb", "total"], rows)

    # -- blade passage harmonics on the A-weighting curve ---------------------
    bpf = rep["bpf"]
    rows = [(k, k * bpf, acoustics.a_weighting(k * bpf)) for k in range(1, 7)]
    write_table(out_dir, "c_harm", ["k", "f", "A"], rows)
    rows = [(f, acoustics.a_weighting(float(f))) for f in np.geomspace(10.0, 20000.0, 200)]
    write_table(out_dir, "c_aweight", ["f", "A"], rows)

    # -- how much the least certain constant, k_c, can move the design --------
    masses = []
    for kc_try in (0.5, 6.0):
        r_kc = C.close_first_principles(dict(p, ceiling_k=kc_try))
        masses.append(r_kc["m"] if r_kc["feasible"] else float("nan"))
    kc_span_g = 1e3 * abs(masses[1] - masses[0])

    # -- motor mass against torque ---------------------------------------------
    k_tau = float(p["motor_torque_density"])
    e = float(p["motor_scale_exp"])
    rows = []
    for Qm in np.geomspace(0.02, 5.0, 80):
        m_mot = C.motor_mass_for_torque(p, float(Qm))
        m_lin = float(Qm) / k_tau          # constant torque density, e = 0
        rows.append((Qm, 1e3 * m_mot, 1e3 * m_lin))
    write_table(out_dir, "c_motor", ["Q", "mmot", "mlin"], rows)
    Q_design = pr.Q_max
    m_mot_design = pr.m_motor_each

    # -- geometry and operating point ------------------------------------------
    com = inert["center_of_mass"]
    so = veh.screen_offset
    T_rotor = m * g / N
    T_rotor_max = float(p["lam"]) * T_rotor
    z_rotor = C.rotor_plane_height(p)
    ceil_gap = float(p["ceiling_height"]) - z_rotor
    kc = float(p["ceiling_k"])
    ceil_pct = 100.0 * (1.0 - 1.0 / surf["k_ceiling"])
    ground_pct = 100.0 * (1.0 - 1.0 / surf["k_ground"])
    values = dict(
        cM="%.3f" % m, cMbat="%.3f" % m_bat,
        cL="%.4f" % arm.L, cR="%.4f" % R, cReach="%.3f" % (arm.L + R),
        cSpan="%.3f" % arm.span, cKgap="%.3f" % float(p["rotor_gap"]),
        cGap="%.4f" % inter["gap"], cSoverD="%.3f" % inter["gap_ratio"],
        cKint="%.4f" % inter["kappa_int"],
        cRcp="%.3f" % float(p["r_cp"]), cCoMz="%.4f" % com[2],
        cScreenOffz="%.4f" % so[2],
        cScreenW="%.3f" % float(p["screen_w"]), cScreenH="%.3f" % float(p["screen_h"]),
        cArmr="%.1f" % (1e3 * float(p["arm_radius"])),
        cWall="%.2f" % (1e3 * arm.wall), cWallStress="%.3f" % (1e3 * arm.wall_stress),
        cWallStiff="%.3f" % (1e3 * arm.wall_stiff), cWallMin="%.2f" % (1e3 * float(p["wall_min"])),
        cDriver=arm.driver, cSigmaWork="%.0f" % (arm.sigma / 1e6),
        cSigmaAllow="%.0f" % float(p["sigma_allow"]),
        cFbend="%.0f" % arm.f_bending,
        cFlimit="%.1f" % (float(p["SF_struct"]) * T_rotor_max),
        cZrotor="%.2f" % z_rotor, cZceil="%.2f" % ceil_gap,
        cZoverR="%.2f" % (z_rotor / R), cZcOverR="%.2f" % (ceil_gap / R),
        cKground="%.4f" % surf["k_ground"], cKceiling="%.4f" % surf["k_ceiling"],
        cKc="%.1f" % kc, cCeilPct="%.1f" % ceil_pct, cGroundPct="%.2f" % ground_pct,
        cKcSpanG="%.0f" % kc_span_g,
        cCeiling="%.1f" % float(p["ceiling_height"]),
        cBpf="%.1f" % bpf, cRpm="%.0f" % hov.rpm, cNb="%d" % int(round(float(p["n_blades"]))),
        cAbpf="%.1f" % acoustics.a_weighting(bpf),
        cLwa="%.1f" % L_W, cRroom="%.1f" % Rroom, cRc="%.2f" % rep["critical_distance"],
        cStandoff="%.2f" % float(p["standoff"]), cSplEar="%.1f" % rep["at_listener"]["total"],
        cSplOne="%.1f" % rep["free_field_1m"]["total"], cSplFar="%.1f" % rep["far_field"]["total"],
        cTrotor="%.2f" % T_rotor, cVtip="%.1f" % hov.v_tip, cAnchor="%.1f" % C._SPL_REF,
        cVi="%.2f" % hov.v_induced,
        cTfCross="%.0f" % cross, cTf="%.0f" % (float(p["t_f"]) / 60.0),
        cQmax="%.3f" % Q_design, cMmot="%.0f" % (1e3 * m_mot_design),
        cKtau="%.1f" % k_tau, cEmot="%.2f" % e,
        cRoomL="%.0f" % float(p["room_length"]), cRoomW="%.0f" % float(p["room_width"]),
        cAlphaRoom="%.2f" % float(p["room_alpha"]),
    )
    _defs(out_dir, "c_geom", values)


if __name__ == "__main__":
    generate(default_out())
